### PR TITLE
Enable Player subclassing.

### PR DESCRIPTION
**Pull request by LarsStegman**
We want to be able to extend the Player class so that we are able to add properties to Players.

### CODE REVIEW

**Comment by LarsStegman** [comment]
We'd like to commit our extra assignment, but the build will fail without these adjustments. Have you had a look at them yet?

**Comment by JWGmeligMeyling** [comment]
Please update the version number in the pom file to something that identifies your group. Then use that version number in the pom file of your solution. I will deploy this version of the framework to our maven repositories, I expect this to be applied around midnight. After the changes I will rebuild your failed builds. If the artefact/versions numbers are set correct, they should succeed then.

**Comment by JWGmeligMeyling** [comment]
Push this version number to a new commit and possibly on a new branch so that we can still merge in this PR :)

**Comment by LarsStegman** [comment]
From which commit do you want me to branch?

**Comment by JWGmeligMeyling** [comment]
Branch from this branch, and add another commit with the version number `6.3.0-group-#` or so.

**Comment by LarsStegman** [comment]
Done. The branch name is `PlayerSubclassingVersionUpdate`.

**Comment by JWGmeligMeyling** [comment]
Deployed!
```xml
<dependency>
  <groupId>nl.tudelft.jpacman</groupId>
  <artifactId>jpacman-framework</artifactId>
  <version>6.3.1-GROUP6</version>
</dependency>
```

**Pull request merged**
